Add some basic error checking on each step of the make world process

diff --git a/RELENG_10/scripts/installkernel b/RELENG_10/scripts/installkernel
--- a/RELENG_10/scripts/installkernel
+++ b/RELENG_10/scripts/installkernel
@@ -1,18 +1,26 @@
 #!/bin/sh
+# Installs the kernel built with make buildkernel
 
-echo "Kernel Installation Begun: `date +%c`";
-if [ "$#" -eq 0 ]; then
-    KERNCONF=`uname -i`;
-fi;
+echo "Kernel Installation Begun: $(date +%c)";
+
+KERNCONF=$(uname -i);
+
 if [ "$#" -gt 0 ]; then
     KERNCONF=$1;
 fi;
+
 if [ "$KERNCONF" == "GENERIC" ]; then
     echo "Please choose the custom kernel";
     echo "Kernel Installation Failed: `date +%c`";
-    exit 255;
+    exit 13;
 fi;
+
 cd /usr/src
 make installkernel KERNCONF=$KERNCONF;
 
-echo "Kernel Installation Ended: `date +%c`";
+if [ $? -ne 0 ]; then
+    echo "make installkernel KERNCONF=$KERNCONF failed"
+    exit 1;
+fi; 
+
+echo "Kernel Installation Ended: $(date +%c)";
diff --git a/RELENG_10/scripts/installworld b/RELENG_10/scripts/installworld
--- a/RELENG_10/scripts/installworld
+++ b/RELENG_10/scripts/installworld
@@ -1,11 +1,24 @@
 #!/bin/sh
 # Run after the FreeBSD make world and kernel build/installs are done in makeworld.sh
 # Best if run in Single User Mode.
-KERNCONF='NAS_10'
+
 cd /usr/src
 $HOME/bin/installkernel
+
+if [ $? -ne 0 ]; then
+    echo "Failed installing the Kernel"
+    exit 1;
+fi; 
+
 make installworld
+
+if [ $? -ne 0 ]; then
+    echo "Failed installing the World"
+    exit 1;
+fi; 
+
 cd /usr/src/usr.sbin/mergemaster
 ./mergemaster.sh -Ui
 echo "Install World Completed: Rebooting"
+date +%c
 fastboot
diff --git a/RELENG_10/scripts/makekernel b/RELENG_10/scripts/makekernel
--- a/RELENG_10/scripts/makekernel
+++ b/RELENG_10/scripts/makekernel
@@ -1,19 +1,26 @@
 #!/bin/sh
+# Builds the FreeBSD Kernel
 
-echo "Kernel Build Begun: `date +%c`";
-if [ "$#" -eq 0 ]; then
-    KERNCONF=`uname -i`;
-fi;
+echo "Kernel Build Begun: $(date +%c)";
+
+KERNCONF=$(uname -i);
+
 if [ "$#" -gt 0 ]; then
     KERNCONF=$1;
 fi;
+
 if [ "$KERNCONF" == "GENERIC" ]; then
     echo "Please choose the custom kernel";
-    echo "Kernel Build Ended: `date +%c`";
-    exit 255;
+    echo "Kernel Build Ended: $(date +%c)";
+    exit 13;
 fi;
 cd /usr/src
 echo $KERNCONF;
 make buildkernel KERNCONF=$KERNCONF;
 
-echo "Kernel Build Ended: `date +%c`";
+if [ $? -ne 0 ]; then
+    echo "make buildkernel KERNCONF=$KERNCONF failed"
+    exit 1;
+fi; 
+
+echo "Kernel Build Ended: $(date +%c)";
diff --git a/RELENG_10/scripts/makeworld b/RELENG_10/scripts/makeworld
--- a/RELENG_10/scripts/makeworld
+++ b/RELENG_10/scripts/makeworld
@@ -1,16 +1,30 @@
 #!/bin/sh
 # Performs a Handbook make world:
 # http://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/makeworld.html
-KERNCONF='NAS_10'
+
+echo "Beginning the make world process: $(date +%c)"
 CPU=$(sysctl -n hw.ncpu); 
 JOBS=$(( $CPU + 1 ));
 
 cd /usr/src/usr.sbin/mergemaster
 /bin/sh mergemaster.sh -p
 adjkerntz -i
+
 cd /usr/src
 make -j${JOBS} buildworld
+
+if [ $? -ne 0 ]; then
+    echo "Failed Compiling the World"
+    exit 1;
+fi; 
+
 $HOME/bin/makekernel
+
+if [ $? -ne 0 ]; then
+    echo "Failed installing the Kernel"
+    exit 1;
+fi; 
+
 echo "Build World, and Kernel Rebuilds Complete"
-echo "Boot into Single User Mode Now, and run $HOME/bin/installworld.sh to complete upgrade"
+echo "Maybe boot into Single User Mode Now, and run $HOME/bin/installworld.sh to complete upgrade"
 # shutdown now
